from types import SimpleNamespace

from torch.nn.functional import one_hot


HYPERPARAMS = {
    
    'simple_spread': SimpleNamespace(**{
        'scenario_name':         "simple_spread",
        'max_episode_len': 25,
        'time_steps':       500000,
        'num_adversaries':  0,
        'lr_actor':        1e-4,
        'lr_critic':       1e-3,
        'epsilon':         0.1,
        'noise_rate':      0.1,
        'gamma':           0.95,
        'tau':              0.01,
        'buffer_size':      2049,
        'batch_size':      2049,
        'save_dir':        "./Experiments",
        'save_rate':       1000,
        'model_dir':       "",
        'evaluate_episodes':  10,
        'evaluate_episode_len': 100,
        'evaluate':         False,
        'evaluate_rate':       200,
        'update_freq':      30,
        'cuda':             False,
        'hidden_dim':        64, 
        'attend_heads':       4,
        'norm_in':           False,  
        'n_agents':           3,
        'n_threads':          1,
        'steps_update':       1,
        'target_update':      30,
        'discrete_action':    False, 
        'use_feature_normalization' : False,
        'use_orthogonal': False,
        'use_ReLU': True,
        'stacked_frames': False,
        'layer_N': 2,
        'hidden_size': 64, 
        'ppo_eps': 0.2,
        'gae_lambda': 0.9,
        'ppo_epoches': 10,
        'ppo_batch_size': 256, 
        'entropy_coeff': 0.01, 
        'global_state': False,
        'gain': 0.01, 
        'mixed': False,
        'one_hot': True,
        'env_ending': False, 
        'mpe': True, 
        'multi_discrete': False, 
        'use_load_model': False, 
        'reward_size': 1
        }), 
        
    'Switch4-v0': SimpleNamespace(**{
        'scenario_name':         "Switch2-v0",
        'max_episode_len': 25,
        'time_steps':       500000,
        'num_adversaries':  0,
        'lr_actor':        1e-4,
        'lr_critic':       1e-3,
        'epsilon':         0.1,
        'noise_rate':      0.1,
        'gamma':           0.95,
        'tau':              0.01,
        'buffer_size':      2049,
        'batch_size':      2049,
        'save_dir':        "./Experiments",
        'save_rate':       1000,
        'model_dir':       "",
        'evaluate_episodes':  10,
        'evaluate_episode_len': 100,
        'evaluate':         False,
        'evaluate_rate':       200,
        'update_freq':      30,
        'cuda':             False,
        'hidden_dim':        64, 
        'attend_heads':       4,
        'norm_in':           False,  
        'n_agents':           2,
        'n_threads':          1,
        'steps_update':       1,
        'target_update':      30,
        'discrete_action':    False, 
        'use_feature_normalization' : False,
        'use_orthogonal': False,
        'use_ReLU': True,
        'stacked_frames': False,
        'layer_N': 2,
        'hidden_size': 64, 
        'ppo_eps': 0.2,
        'gae_lambda': 0.9,
        'ppo_epoches': 10,
        'ppo_batch_size': 256, 
        'entropy_coeff': 0.01, 
        'global_state': False,
        'gain': 0.01, 
        'mixed': False,
        'one_hot': False,
        'env_ending': True, 
        'mpe': True, 
        'multi_discrete': False, 
        'use_load_model': False, 
        'reward_size': 1})}